owner: graueneko
repo: status-page

sites:
  - name: GrauNeko.com
    url: https://graueneko.com
  - name: FreshRss
    url: https://rrss.gneko.app
  - name: RssHub
    url: https://rsshub.gneko.app
  - name: Bark
    url: https://bark.gneko.app/ping
  - name: ChatGPT
    url: $SITE_CHATGPT
  - name: ChatGPT-Azure
    url: $SITE_CHATGPT_AZURE

status-website:
  cname: status.gneko.dev
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: GNeko Services Status
  introTitle: Services offered by [GNeko](https://github.com/gneko).
  introMessage: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/gneko
